### PR TITLE
Add GitHub Actions build workflow

### PR DESCRIPTION
**Pull request by maximelouet**

### CODE REVIEW

**Comment by maximelouet** [comment]
> lgtm!

How did you see the result? I can't find it in "Checks", I can only find a pending one

**Comment by maximelouet** [comment]
image

**Comment by maximelouet** [comment]
I don't know what you looked at but it definitely doesn't look good

**Comment by AnastasiaPromtep** [comment]
No I just read the file, I assumed it was working since you are asking for a review.

**Pull request merged**
